language: rust
os: linux
dist: xenial
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: stable
    - rust: beta
  fast_finish: true
cache: cargo
before_install:
  - rustup component add clippy rustfmt
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo fmt -- --verbose --check
  - cargo clippy --verbose