language: rust
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: [stable, beta]
  fast_finish: true
cache: cargo
before_install:
  - rustup component add clippy rustfmt
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo fmt -- --verbose --check
  - cargo clippy --verbose